### ISSUE TITLE
How to remove (uninstall) nginx_ensite from Ubuntu?

### ISSUE THREAD

**Issue by jasomdotnet** [perusio/nginx_ensite#18]
I decided to not use Nginx, so what's to command for nginx_ensite removing (uninstallion)? Tnx

**Comment by Erutan409** [comment]
*bump*

Any word on this?

**Comment by Erutan409** [comment]
Try doing:

`sudo make uninstall`

**Comment by jasomdotnet** [comment]
I don't remember why I have needed this 'nginx_ensite' :)

**Comment by Erutan409** [comment]
I like it just for the convenience of doing a couple of things for me, automatically.
